### ISSUE TITLE
I have Error: account/login-panel/server.lua:372: attempt to call global 'bcrypt_gensalt' (a nil value)

### ISSUE THREAD

**Issue by KIUPIK** [OwlGamingCommunity/MTA#7]
Hi i got this error on 32 bit and 64 bit linux server? Does anyone have a solution?

**Comment by GilroyMTA** [comment]
Same here. When you fix 372, 96 pops out as an error.

**Comment by GilroyMTA** [comment]
No. Just waiting for the answer here.
